app.config(config);
function config($stateProvider,$urlRouterProvider) {
    $stateProvider.state("login",{
       url:"/login",
       templateUrl:"templates/login.html",
       controller:"loginController"
    })
        .state("home",{
            url:"/home",
            templateUrl:"templates/home.html",
            controller:"homeController"
        })
        .state("home.about",{
            url:"/about",
            templateUrl:"templates/about.html",
            controller:"aboutController"
        })
        .state("home.portfolio",{
            url:"/portfolio",
            templateUrl:"templates/portfolio.html",
            controller:"portfolioController"
        })
        .state("home.feedback",{
            url:"/feedback",
            templateUrl:"templates/feedback.html",
            controller:"feedbackController"
        });

    $urlRouterProvider.otherwise("/login");
}